### ISSUE TITLE
bug in setter weights - class Layer 

### ISSUE THREAD

**Issue by gaetanoantonicchio** [AlexPasqua/NNs-from-scratch#23]
bug in network.py

setter weights in Layer doesn't work... needs to be checked

**Comment by AlexPasqua** [comment]
Non funzionava perché aggiornava i pesi delle units, ma non il campo `weights` di `Layer`, che restava settato al valore precedente.
Si può, alternativamente:
- Aggiornare anche il campo `weights `di `Layer`
- Eliminare il campo `weights`, lasciare il getter e il setter facendo in modo che lavorino direttamente con `Unit.w`

Nella PR linkata ho già implementato il secondo modo
